linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - goheader
    - errcheck
    - gocyclo
    - revive
    - gosec
    - gosimple
    - lll
    - misspell
    - prealloc
    - typecheck
