// Code generated by "stringer -type=AttributeType"; DO NOT EDIT.

package conntrack

import "strconv"

const _AttributeType_name = "ctaUnspecctaTupleOrigctaTupleReplyctaStatusctaProtoInfoctaHelpctaNatSrcctaTimeoutctaMarkctaCountersOrigctaCountersReplyctaUsectaIDctaNatDstctaTupleMasterctaSeqAdjOrigctaSeqAdjReplyctaSecMarkctaZonectaSecCtxctaTimestampctaMarkMaskctaLabelsctaLabelsMaskctaSynProxy"

var _AttributeType_index = [...]uint16{0, 9, 21, 34, 43, 55, 62, 71, 81, 88, 103, 119, 125, 130, 139, 153, 166, 180, 190, 197, 206, 218, 229, 238, 251, 262}

func (i AttributeType) String() string {
	if i >= AttributeType(len(_AttributeType_index)-1) {
		return "AttributeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttributeType_name[_AttributeType_index[i]:_AttributeType_index[i+1]]
}
