// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package conntrack

import "strconv"

const _EventType_name = "EventNewEventUpdateEventDestroyEventExpNewEventExpDestroy"

var _EventType_index = [...]uint8{0, 8, 19, 31, 42, 57}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
