// Code generated by "stringer -type=ExpectType"; DO NOT EDIT.

package conntrack

import "strconv"

const _ExpectType_name = "CTAExpectUnspecCTAExpectMasterCTAExpectTupleCTAExpectMaskCTAExpectTimeoutCTAExpectIDCTAExpectHelpNameCTAExpectZoneCTAExpectFlagsCTAExpectClassCTAExpectNATCTAExpectFN"

var _ExpectType_index = [...]uint8{0, 15, 30, 44, 57, 73, 84, 101, 114, 128, 142, 154, 165}

func (i ExpectType) String() string {
	if i >= ExpectType(len(_ExpectType_index)-1) {
		return "ExpectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpectType_name[_ExpectType_index[i]:_ExpectType_index[i+1]]
}
