// Code generated by "stringer -type=TupleType"; DO NOT EDIT.

package conntrack

import "strconv"

const _TupleType_name = "ctaTupleUnspecctaTupleIPctaTupleProtoctaTupleZone"

var _TupleType_index = [...]uint8{0, 14, 24, 37, 49}

func (i TupleType) String() string {
	if i >= TupleType(len(_TupleType_index)-1) {
		return "TupleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TupleType_name[_TupleType_index[i]:_TupleType_index[i+1]]
}
